export const MIN_CARBOHYDRATES = 'MIN_CARBOHYDRATES'
export const MIN_PROTEINS = 'MIN_PROTEINS'
export const MIN_FATS = 'MIN_FATS'
export const MIN_SALT = 'MIN_SALT'
export const MAX_SALT = 'MAX_SALT'
export const MIN_ROUGHAGE = 'MIN_ROUGHAGE'
export const MAX_ROUGHAGE = 'MAX_ROUGHAGE'
export const CONTAIN_WORDS = 'CONTAIN_WORDS'
